### PR TITLE
composer: Nette ~2.1 dependency allowed

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #1

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ping @vojtech-dobes

**Comment by TomasVotruba** [comment]
Ping: Nette 2.3 is here

**Comment by vojtech-dobes** [comment]
Thanks for reminder! Installation with Nette 2.3 allowed.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request closed without merging**
